// playground/svelte/components/TestSection.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        title: string;
        description: string;
        children: Snippet;
    }

    let { title, description, children }: Props = $props();
</script>

<section class="border-t border-gray-200 py-6 first:border-t-0 first:pt-0">
    <h2 class="text-base font-semibold text-gray-900">{title}</h2>
    <p class="mt-1 text-sm text-gray-600">{description}</p>
    <div class="mt-3">
        {@render children()}
    </div>
</section>

// playground/react/components/TestSection.tsx
import { ReactNode } from 'react';

type Props = {
    title: string;
    description: string;
    children: ReactNode;
};

export function TestSection({ title, description, children }: Props) {
    return (
        <section className="border-t border-gray-200 py-6 first:border-t-0 first:pt-0">
            <h2 className="text-base font-semibold text-gray-900">{title}</h2>
            <p className="mt-1 text-sm text-gray-600">{description}</p>
            <div className="mt-3">{children}</div>
        </section>
    );
}
