// playground/react/AsyncErrorButton.tsx
import { useEffect, useState } from 'react';

import { Button } from './Button';

export function AsyncErrorButton() {
    const [trigger, setTrigger] = useState(false);

    useEffect(() => {
        if (trigger) {
            setTrigger(false);
            console.log('Triggering async error in useEffect');
            Promise.reject(new Error('Async error in React useEffect'));
        }
    }, [trigger]);

    return (
        <Button
            onClick={() => {
                setTrigger(true);
            }}
        >
            Async error in useEffect
        </Button>
    );
}

// playground/vue/AsyncErrorButton.vue
<script lang="ts" setup>
import { onMounted, ref, watch } from 'vue';

import Button from './Button.vue';

const trigger = ref(false);

watch(trigger, (value) => {
    if (value) {
        trigger.value = false;
        console.log('Triggering async error in watch');
        Promise.reject(new Error('Async error in Vue watch'));
    }
});
</script>

<template>
    <Button @click="trigger = true">Async error in watch</Button>
</template>
