// playgrounds/nextjs/src/app/confirmation/page.tsx
import { testIds } from '@flareapp/playgrounds-shared';
import Link from 'next/link';

export default function ConfirmationPage() {
    return (
        <section data-testid={testIds.confirmation} className="text-center py-16">
            <h1 className="text-2xl font-semibold mb-2">Order confirmed</h1>
            <p className="text-sm opacity-70 mb-6">A receipt was sent to your inbox.</p>
            <Link href="/" className="text-sm text-brand hover:underline">
                Continue shopping
            </Link>
        </section>
    );
}

// playgrounds/svelte/src/routes/confirmation/+page.svelte
<script lang="ts">
    import { testIds } from '@flareapp/playgrounds-shared';
</script>

<section class="text-center py-16" data-testid={testIds.confirmation}>
    <h1 class="text-2xl font-semibold mb-2">Order confirmed</h1>
    <p class="text-sm opacity-70 mb-6">A receipt was sent to your inbox.</p>
    <a href="/" class="text-sm text-brand hover:underline">Continue shopping</a>
</section>
