// packages/svelte/src/FlareErrorBoundary.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';

    import { __flareRegisterComponent, getComponentTreeContext } from './componentTree.js';
    import { createFlareErrorHandler, type FlareErrorHandlerOptions } from './createFlareErrorHandler.js';

    interface Props {
        children: Snippet;
        failed?: Snippet<[error: Error, reset: () => void]>;
        resetKeys?: unknown[];
        flare?: FlareErrorHandlerOptions['flare'];
        beforeEvaluate?: FlareErrorHandlerOptions['beforeEvaluate'];
        beforeSubmit?: FlareErrorHandlerOptions['beforeSubmit'];
        afterSubmit?: FlareErrorHandlerOptions['afterSubmit'];
        onReset?: (error: Error | null) => void;
    }

    let {
        children,
        failed: fallbackSnippet,
        resetKeys,
        flare,
        beforeEvaluate,
        beforeSubmit,
        afterSubmit,
        onReset,
    }: Props = $props();

    let currentError: Error | null = $state(null);
    let resetBoundary: (() => void) | null = $state(null);

    let previousKeys: unknown[] | undefined;
    $effect(() => {
        if (!currentError || !resetKeys) {
            previousKeys = resetKeys ? [...resetKeys] : undefined;
            return;
        }

        const lengthChanged = previousKeys?.length !== resetKeys.length;
        const valuesChanged = resetKeys.some((key, i) => !Object.is(key, previousKeys?.[i]));

        if (lengthChanged || valuesChanged) {
            handleReset();
        }

        previousKeys = [...resetKeys];
    });

    function handleReset() {
        const error = currentError;
        currentError = null;
        onReset?.(error);
        resetBoundary?.();
        resetBoundary = null;
    }

    const ancestor = __flareRegisterComponent('FlareErrorBoundary', '@flareapp/svelte/FlareErrorBoundary.svelte');

    const handler = $derived(
        createFlareErrorHandler({ ancestor, flare, beforeEvaluate, beforeSubmit, afterSubmit }),
    );

    function onerror(rawError: unknown, reset: () => void) {
        resetBoundary = reset;
        const error = rawError instanceof Error ? rawError : new Error(String(rawError));
        currentError = error;

        handler(rawError, reset);
    }
</script>

<svelte:boundary {onerror}>
    {@render children()}

    {#snippet failed(error, reset)}
        {#if fallbackSnippet}
            {@render fallbackSnippet(error instanceof Error ? error : new Error(String(error)), handleReset)}
        {/if}
    {/snippet}
</svelte:boundary>

// packages/react/src/FlareErrorBoundary.ts
import { flare } from '@flareapp/js';
import { Component, ErrorInfo, type PropsWithChildren, type ReactNode } from 'react';

import { formatComponentStack } from './format-component-stack';
import { parseComponentStack } from './parse-component-stack';
import { FlareReactContext } from './types';

export type FlareErrorBoundaryFallbackProps = {
    error: Error;
    componentStack: string[];
    resetErrorBoundary: () => void;
};

export type FlareErrorBoundaryProps = PropsWithChildren<{
    fallback?: ReactNode | ((props: FlareErrorBoundaryFallbackProps) => ReactNode);
    resetKeys?: unknown[];
    beforeEvaluate?: (params: { error: Error; errorInfo: ErrorInfo }) => void;
    beforeSubmit?: (params: { error: Error; errorInfo: ErrorInfo; context: FlareReactContext }) => FlareReactContext;
    afterSubmit?: (params: { error: Error; errorInfo: ErrorInfo; context: FlareReactContext }) => void;
    onReset?: (error: Error | null) => void;
}>;

export type FlareErrorBoundaryState = {
    error: Error | null;
    componentStack: string[];
};

export class FlareErrorBoundary extends Component<FlareErrorBoundaryProps, FlareErrorBoundaryState> {
    state: FlareErrorBoundaryState = { error: null, componentStack: [] };

    static getDerivedStateFromError(error: Error): Partial<FlareErrorBoundaryState> {
        return { error };
    }

    componentDidCatch(error: Error, errorInfo: ErrorInfo) {
        this.props.beforeEvaluate?.({
            error,
            errorInfo,
        });

        const rawStack = errorInfo.componentStack ?? '';

        const context: FlareReactContext = {
            react: {
                componentStack: formatComponentStack(rawStack),
                componentStackFrames: parseComponentStack(rawStack),
            },
        };

        const finalContext =
            this.props.beforeSubmit?.({
                error,
                errorInfo,
                context,
            }) ?? context;

        this.setState({ componentStack: finalContext.react.componentStack });

        flare.report(error, finalContext, { react: { errorInfo } });

        this.props.afterSubmit?.({
            error,
            errorInfo,
            context: finalContext,
        });
    }

    componentDidUpdate(prevProps: FlareErrorBoundaryProps) {
        if (this.state.error === null || !this.props.resetKeys) {
            return;
        }

        const prevKeys = prevProps.resetKeys;
        const nextKeys = this.props.resetKeys;

        const lengthChanged = prevKeys?.length !== nextKeys.length;
        const valuesChanged = nextKeys.some((key, i) => !Object.is(key, prevKeys?.[i]));

        if (lengthChanged || valuesChanged) {
            this.reset();
        }
    }

    reset = () => {
        const { error } = this.state;

        this.props.onReset?.(error);

        this.setState({ error: null, componentStack: [] });
    };

    render() {
        const { error } = this.state;

        if (error !== null) {
            const { fallback } = this.props;

            if (typeof fallback === 'function') {
                return fallback({
                    error,
                    componentStack: this.state.componentStack,
                    resetErrorBoundary: this.reset,
                });
            }

            return fallback ?? null;
        }

        return this.props.children;
    }
}
