// playground/react/sections/AsyncErrorSection.tsx
import { useEffect, useState } from 'react';

import { Button } from '../components/Button';
import { TestSection } from '../components/TestSection';

export function AsyncErrorSection() {
    const [trigger, setTrigger] = useState(false);

    useEffect(() => {
        if (trigger) {
            setTrigger(false);
            console.log('Triggering async error in useEffect');
            Promise.reject(new Error('Async error in React useEffect'));
        }
    }, [trigger]);

    return (
        <TestSection
            title="Async error in useEffect"
            description="Triggers an unhandled promise rejection from inside useEffect. Captured via window.onunhandledrejection."
        >
            <Button onClick={() => setTrigger(true)}>Async error in useEffect</Button>
        </TestSection>
    );
}

// playground/svelte/sections/AsyncErrorSection.svelte
<script lang="ts">
    import Button from '../components/Button.svelte';
    import TestSection from '../components/TestSection.svelte';
</script>

<TestSection
    title="Async error"
    description="Triggers an unhandled promise rejection. Captured via window.onunhandledrejection."
>
    <Button
        onclick={() => {
            console.log('Triggering async error');
            Promise.reject(new Error('Async error in Svelte component'));
        }}
    >
        Async error (unhandled rejection)
    </Button>
</TestSection>
