// playgrounds/nextjs/src/app/checkout/page.tsx
'use client';

import { testIds } from '@flareapp/playgrounds-shared';
import { useRouter } from 'next/navigation';
import type { FormEvent } from 'react';

import { cart } from '@/cart';

export default function CheckoutPage() {
    const router = useRouter();

    const onSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        cart.clear();
        router.push('/confirmation');
    };

    return (
        <section className="max-w-md mx-auto">
            <h1 className="text-xl font-semibold mb-6">Checkout</h1>
            <form onSubmit={onSubmit} className="flex flex-col gap-4">
                <label className="flex flex-col gap-1 text-sm">
                    Name
                    <input
                        name="name"
                        required
                        defaultValue="Test User"
                        className="rounded border border-surface-border px-3 py-2"
                    />
                </label>
                <label className="flex flex-col gap-1 text-sm">
                    Email
                    <input
                        name="email"
                        type="email"
                        required
                        defaultValue="test@example.com"
                        className="rounded border border-surface-border px-3 py-2"
                    />
                </label>
                <label className="flex flex-col gap-1 text-sm">
                    Card number
                    <input
                        name="card"
                        required
                        defaultValue="4242 4242 4242 4242"
                        className="rounded border border-surface-border px-3 py-2 font-mono"
                    />
                </label>
                <button
                    type="submit"
                    data-testid={testIds.checkoutSubmit}
                    className="rounded-lg bg-brand-ink text-white py-2 text-sm"
                >
                    Pay
                </button>
            </form>
        </section>
    );
}

// playgrounds/svelte/src/routes/checkout/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { testIds } from '@flareapp/playgrounds-shared';
    import { cart } from '$lib/cart.svelte';

    const onSubmit = (event: SubmitEvent): void => {
        event.preventDefault();
        cart.clear();
        void goto('/confirmation');
    };
</script>

<section class="max-w-md mx-auto">
    <h1 class="text-xl font-semibold mb-6">Checkout</h1>
    <form onsubmit={onSubmit} class="flex flex-col gap-4">
        <label class="flex flex-col gap-1 text-sm">
            Name
            <input
                name="name"
                required
                value="Test User"
                class="rounded border border-surface-border px-3 py-2"
            />
        </label>
        <label class="flex flex-col gap-1 text-sm">
            Email
            <input
                name="email"
                type="email"
                required
                value="test@example.com"
                class="rounded border border-surface-border px-3 py-2"
            />
        </label>
        <label class="flex flex-col gap-1 text-sm">
            Card number
            <input
                name="card"
                required
                value="4242 4242 4242 4242"
                class="rounded border border-surface-border px-3 py-2 font-mono"
            />
        </label>
        <button
            type="submit"
            data-testid={testIds.checkoutSubmit}
            class="rounded-lg bg-brand-ink text-white py-2 text-sm"
        >
            Pay
        </button>
    </form>
</section>
