// playgrounds/react/src/components/Layout.tsx
import { testIds } from '@flareapp/playgrounds-shared';
import { useCartCount } from '@flareapp/playgrounds-shared/react';
import { Link, Outlet } from '@tanstack/react-router';

export const Layout = () => {
    const count = useCartCount();

    return (
        <div className="min-h-screen flex flex-col">
            <header className="border-b border-surface-border bg-surface">
                <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
                    <Link to="/" className="text-lg font-semibold tracking-tight">
                        Flare Pix
                    </Link>
                    <nav className="flex items-center gap-6">
                        <Link to="/" className="text-sm font-medium hover:text-brand">
                            Shop
                        </Link>
                        <Link to="/cart" className="text-sm font-medium hover:text-brand">
                            Cart
                        </Link>
                        <Link to="/broken" className="text-sm font-medium hover:text-brand">
                            Broken
                        </Link>
                        <Link to="/http" className="text-sm font-medium hover:text-brand">
                            HTTP
                        </Link>
                        <Link
                            to="/cart"
                            data-testid={testIds.cartCount}
                            className="rounded-full bg-brand px-3 py-1 text-xs font-semibold text-white"
                        >
                            {count}
                        </Link>
                    </nav>
                </div>
            </header>
            <main className="flex-1 mx-auto max-w-5xl w-full px-6 py-8">
                <Outlet />
            </main>
        </div>
    );
};

// playgrounds/vue/src/components/Layout.vue
<script setup lang="ts">
import { testIds } from '@flareapp/playgrounds-shared';
import { FlareErrorBoundary } from '@flareapp/vue';
import { RouterLink, RouterView } from 'vue-router';

import { clearBrokenTrigger } from '../brokenTrigger';
import { useCart } from '../cart';
import Fallback from './Fallback.vue';

const cart = useCart();

const onBoundaryReset = (): void => {
    clearBrokenTrigger();
};
</script>

<template>
    <div class="min-h-screen flex flex-col">
        <header class="border-b border-surface-border bg-surface">
            <div class="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
                <RouterLink to="/" class="text-lg font-semibold tracking-tight">Flare Pix</RouterLink>
                <nav class="flex items-center gap-6">
                    <RouterLink to="/" class="text-sm font-medium hover:text-brand">Shop</RouterLink>
                    <RouterLink to="/cart" class="text-sm font-medium hover:text-brand">Cart</RouterLink>
                    <RouterLink to="/broken" class="text-sm font-medium hover:text-brand">Broken</RouterLink>
                    <RouterLink to="/http" class="text-sm font-medium hover:text-brand">HTTP</RouterLink>
                    <RouterLink
                        to="/cart"
                        class="rounded-full bg-brand px-3 py-1 text-xs font-semibold text-white"
                        :data-testid="testIds.cartCount"
                    >
                        {{ cart.count.value }}
                    </RouterLink>
                </nav>
            </div>
        </header>
        <main class="flex-1 mx-auto max-w-5xl w-full px-6 py-8">
            <FlareErrorBoundary :on-reset="onBoundaryReset">
                <RouterView />
                <template #fallback="{ error, resetErrorBoundary }">
                    <Fallback :error="error as Error" :reset-error-boundary="resetErrorBoundary as () => void" />
                </template>
            </FlareErrorBoundary>
        </main>
    </div>
</template>
