// playground/vue/sections/OnClickErrorSection.vue
<script lang="ts" setup>
import Button from '../components/Button.vue';
import TestSection from '../components/TestSection.vue';
</script>

<template>
    <TestSection
        title="Uncaught error in @click handler"
        description="Throws synchronously inside an @click handler. Captured by flareVue via app.config.errorHandler with info='native event handler'."
    >
        <Button
            @click="
                () => {
                    console.log('Throwing error in @click handler');
                    throw new Error('Error in Vue @click handler');
                }
            "
        >
            Throw in @click
        </Button>
    </TestSection>
</template>

// playground/react/sections/OnClickErrorSection.tsx
import { Button } from '../components/Button';
import { TestSection } from '../components/TestSection';

export function OnClickErrorSection() {
    return (
        <TestSection
            title="Uncaught error in an event handler"
            description="Throws synchronously inside onClick. React does not catch event-handler errors, so this is handled by the global window.onerror listener."
        >
            <Button
                onClick={() => {
                    console.log('Throwing error in onClick handler');
                    throw new Error('Error in React onClick handler');
                }}
            >
                Throw in onClick
            </Button>
        </TestSection>
    );
}
