// playground/svelte/sections/OnClickErrorSection.svelte
<script lang="ts">
    import Button from '../components/Button.svelte';
    import TestSection from '../components/TestSection.svelte';
</script>

<TestSection
    title="Uncaught error in an event handler"
    description="Throws synchronously inside onclick. Not caught by the boundary, handled by the global window.onerror listener."
>
    <Button
        onclick={() => {
            console.log('Throwing error in onclick handler');
            throw new Error('Error in Svelte onclick handler');
        }}
    >
        Throw in onclick
    </Button>
</TestSection>

// playground/react/sections/OnClickErrorSection.tsx
import { Button } from '../components/Button';
import { TestSection } from '../components/TestSection';

export function OnClickErrorSection() {
    return (
        <TestSection
            title="Uncaught error in an event handler"
            description="Throws synchronously inside onClick. React does not catch event-handler errors, so this is handled by the global window.onerror listener."
        >
            <Button
                onClick={() => {
                    console.log('Throwing error in onClick handler');
                    throw new Error('Error in React onClick handler');
                }}
            >
                Throw in onClick
            </Button>
        </TestSection>
    );
}
