// playground/react/sections/AsyncErrorSection.tsx
import { useEffect, useState } from 'react';

import { Button } from '../components/Button';
import { TestSection } from '../components/TestSection';

export function AsyncErrorSection() {
    const [trigger, setTrigger] = useState(false);

    useEffect(() => {
        if (trigger) {
            setTrigger(false);
            console.log('Triggering async error in useEffect');
            Promise.reject(new Error('Async error in React useEffect'));
        }
    }, [trigger]);

    return (
        <TestSection
            title="Async error in useEffect"
            description="Triggers an unhandled promise rejection from inside useEffect. Captured via window.onunhandledrejection."
        >
            <Button onClick={() => setTrigger(true)}>Async error in useEffect</Button>
        </TestSection>
    );
}

// playground/vue/sections/AsyncErrorSection.vue
<script lang="ts" setup>
import { ref, watch } from 'vue';

import Button from '../components/Button.vue';
import TestSection from '../components/TestSection.vue';

const trigger = ref(false);

watch(trigger, (value) => {
    if (value) {
        trigger.value = false;
        console.log('Triggering async error in watch');
        Promise.reject(new Error('Async error in Vue watch'));
    }
});
</script>

<template>
    <TestSection
        title="Async error in watcher (Promise rejection)"
        description="Rejects a promise from inside a watcher. Not caught by flareVue's handler; captured via window.onunhandledrejection instead."
    >
        <Button @click="trigger = true">Async error in watch</Button>
    </TestSection>
</template>
