// playground/react/sections/ResetKeysSection.tsx
import { FlareErrorBoundary } from '@flareapp/react';
import { useState } from 'react';

import { Button } from '../components/Button';
import { TestSection } from '../components/TestSection';
import { ConditionallyBuggyComponent } from '../ConditionallyBuggyComponent';

export function ResetKeysSection() {
    const [shouldThrow, setShouldThrow] = useState(false);
    const [resetCounter, setResetCounter] = useState(0);

    return (
        <TestSection
            title="resetKeys auto-reset"
            description="Triggers an error, then increments a resetKey to auto-reset the boundary. The onReset callback fires, and the child re-renders without error."
        >
            <div className="flex flex-wrap items-center gap-3">
                <Button onClick={() => setShouldThrow(true)}>Trigger error</Button>
                <Button
                    onClick={() => {
                        setShouldThrow(false);
                        setResetCounter((c) => c + 1);
                        console.log('Incremented resetKey to', resetCounter + 1);
                    }}
                >
                    Increment resetKey (auto-reset)
                </Button>
            </div>
            <p className="mt-2 text-xs text-gray-500">
                resetCounter: {resetCounter} | shouldThrow: {String(shouldThrow)}
            </p>
            <div className="mt-3">
                <FlareErrorBoundary
                    resetKeys={[resetCounter]}
                    onReset={(error) =>
                        console.log('FlareErrorBoundary onReset via resetKeys, error was:', error?.message)
                    }
                    fallback={({ error }) => (
                        <p className="text-sm text-red-700">
                            Boundary caught: {error.message} — increment resetKey to recover.
                        </p>
                    )}
                >
                    <ConditionallyBuggyComponent shouldThrow={shouldThrow} />
                </FlareErrorBoundary>
            </div>
        </TestSection>
    );
}

// playground/vue/sections/ResetKeysSection.vue
<script lang="ts" setup>
import { FlareErrorBoundary } from '@flareapp/vue';
import { ref } from 'vue';

import BuggyComponent from '../components/BuggyComponent.vue';
import Button from '../components/Button.vue';
import TestSection from '../components/TestSection.vue';

const showBuggy = ref(false);
const resetCounter = ref(0);
</script>

<template>
    <TestSection
        title="resetKeys auto-recovery"
        description="Passes a counter as resetKeys to the boundary. Incrementing it auto-recovers the boundary without the user clicking the fallback's reset button."
    >
        <div class="flex flex-wrap items-center gap-3">
            <Button
                @click="
                    () => {
                        console.log('Triggering render error for resetKeys test');
                        showBuggy = true;
                    }
                "
            >
                Trigger error
            </Button>
            <Button
                @click="
                    () => {
                        resetCounter++;
                        console.log(`Incrementing resetKeys counter to ${resetCounter}`);
                    }
                "
            >
                Increment reset key (counter: {{ resetCounter }})
            </Button>
        </div>
        <div v-if="showBuggy" class="mt-3">
            <FlareErrorBoundary
                :reset-keys="[resetCounter]"
                :on-reset="
                    (error) => {
                        console.log('resetKeys onReset called, previous error:', error?.message);
                        showBuggy = false;
                    }
                "
            >
                <BuggyComponent />
                <template #fallback="{ error }">
                    <p class="text-sm text-red-600">
                        Error caught: {{ error.message }}. Click "Increment reset key" to auto-reset.
                    </p>
                </template>
            </FlareErrorBoundary>
        </div>
    </TestSection>
</template>
